volumes:
  postgres_data:
    driver: local

services:
  postgresql:
    build:
      context: ./postgres/
    shm_size: 1g
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5440:5432
    env_file:
      - ./.env

  drizzle-studio:
    container_name: drizzle-studio
    build: ./drizzle/
    ports:
      - "4983:4983"
    environment:
      DATABASE_URL: postgresql://postgres:rindexer@postgresql:5432/postgres
    depends_on:
      - postgresql
